### PR TITLE
added signup login logout with toast notif

### PR DESCRIPTION
**Pull request by Hnh013**
Added pages : Login , Signup , toast notifications
Added service methods for toast and authentication
Added context for user state 
Added basic routing for login , signup and logout actions

### CODE REVIEW

**Review by hrishi82 — APPROVED** [review]
good code structure,
code can be merged

**Review by ramalingaa — APPROVED** [review]
The functionalities are working, you can focus on css bit more

**Review by OmKakatkar — APPROVED** [review]
Added functinonality is working fine
Like the use of contant file for form content
Overall looks good to merge

**Comment by Hnh013** [comment]
> The functionalities are working, you can focus on css bit more

hi Rama , yes I am trying to improve it :)

**Pull request merged**
